"""empty message

Revision ID: 5e2853e73dea
Revises: 46b2cf2d2d5e
Create Date: 2022-01-24 14:32:15.181409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2853e73dea'
down_revision = '46b2cf2d2d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_master', sa.Column('file_type', sa.String(length=50), nullable=True, comment='파일 Type'))
    op.alter_column('content_master', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               comment='컨텐츠 Type',
               existing_comment='컨텐츠 파일 Type',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_master', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               comment='컨텐츠 파일 Type',
               existing_comment='컨텐츠 Type',
               existing_nullable=True)
    op.drop_column('content_master', 'file_type')
    # ### end Alembic commands ###
